sudo : required 
services : 
  - docker 

before_install : 
  - docker build -t relmanso/docker-react -f Dockerfile.dev . 

script : 
  - docker run -e CI=true relmanso/docker-react npm run test -- --coverage