sudo : required 
services : 
  - docker 

before_install : 
  - gem install rake
  - docker build -t relmanso/docker-react -f Dockerfile.dev . 

script : 
  - docker run relmanso/docker-react npm run test -- --coverage
  - bundle exec rake test